# Generated by Django 3.2.5 on 2021-08-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/')),
                ('status', models.BooleanField(default=False)),
                ('num_faces', models.IntegerField(default=0)),
            ],
        ),
    ]
