# Generated by Django 3.2.5 on 2021-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
