# Generated by Django 3.2.5 on 2021-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_alter_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(default='waiting', max_length=100),
        ),
    ]
