# Generated by Django 3.2.5 on 2021-08-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frame',
            field=models.IntegerField(default=0),
        ),
    ]
