# Generated by Django 3.2.5 on 2021-08-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_video_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='frame',
        ),
        migrations.AddField(
            model_name='video',
            name='task_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
